# -*- coding: utf-8 -*-
"""FIFA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19Dbd9z9CCvah4y7w2KkiXYsd-RXo7sax
"""

import pandas as pd
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount("/content/drive")

fifa = pd.read_csv("/content/players_20.csv")
fifa

fifa.shape

fifa.columns

fifa.columns = [col.capitalize() for col in fifa]
fifa.columns

fifa['Nationality'].value_counts()

fifa['Nationality'].value_counts().head()

fifa[fifa['Nationality'] == 'India'].head()

fifa['Nationality'].value_counts()[0:10].head()

fifa['Nationality'].value_counts()[0:10].keys()

plt.figure(figsize = (8,8))
plt.bar(  list(fifa['Nationality'].value_counts()[0:5].keys()), list(fifa['Nationality'].value_counts()[0:5]), color = ['red','pink','black','green'], width = 0.2)
plt.xlabel('country_name')
plt.ylabel("Value")
plt.title("country_name vs value")

plt.figure(figsize = (15,7))
plt.bar( list(fifa['Short_name'].value_counts()[0:10].keys()), list(fifa['Wage_eur'].value_counts()[0:10]), color = ['red','black','yellow','green','blue','purple','pink','orange','violet','hotpink'],width = 0.4)
plt.xlabel("Short_name")
plt.ylabel("Wage_eur")
plt.title("Short_name  vs  Wage_eur")

India = fifa[fifa['Nationality'] == 'India']
India.head()

India.sort_values(by = ['Age'],ascending=False).head()

India.sort_values(by = ['Height_cm'],ascending = False).head()

India[['Age','Height_cm']].sort_values(by = ['Age'],ascending = False).head()

player_defending=fifa[['Short_name','Defending','Nationality','Club']]
player_defending.sort_values(by = ['Nationality'],ascending = False).head()

fifa[fifa['Club'] == 'India'].sort_values(by = ['Short_name'],ascending = False).head()

India['Nationality'].value_counts()